parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"z2hx":[function(require,module,exports) {

"use strict";var e=function(){if("undefined"!=typeof self)return self;if("undefined"!=typeof window)return window;if(void 0!==t)return t;throw new Error("unable to locate global object")},t=e();module.exports=exports=t.fetch,t.fetch&&(exports.default=t.fetch.bind(t)),exports.Headers=t.Headers,exports.Request=t.Request,exports.Response=t.Response;
},{}],"kpsa":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=t(require("node-fetch"));function t(e){return e&&e.__esModule?e:{default:e}}var r=function(t){var r,o=arguments.length>1&&void 0!==arguments[1]?arguments[1]:1;try{r=window.fetch}catch(n){r=e.default}try{return r("https://spreadsheets.google.com/feeds/cells/".concat(t,"/").concat(o,"/public/values?alt=json-in-script")).then(function(e){if(!e.ok)throw console.log("there is an error in the gsheets response"),new Error("Error fetching GSheet");return e.text()}).then(function(e){var t=e.replace("gdata.io.handleScriptLoaded(","").slice(0,-2);return JSON.parse(t)}).catch(function(e){throw new Error("Failed to fetch from GSheets API. Check your Sheet Id and the public availability of your GSheet.")})}catch(n){throw new Error("General error when fetching GSheet: ".concat(n))}},o=r;exports.default=o;
},{"node-fetch":"z2hx"}],"PoGI":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=t(require("./gsheetsapi.js"));function t(e){return e&&e.__esModule?e:{default:e}}function r(e,t){var r;if("undefined"==typeof Symbol||null==e[Symbol.iterator]){if(Array.isArray(e)||(r=n(e))||t&&e&&"number"==typeof e.length){r&&(e=r);var o=0,u=function(){};return{s:u,n:function(){return o>=e.length?{done:!0}:{done:!1,value:e[o++]}},e:function(e){throw e},f:u}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}var i,a=!0,l=!1;return{s:function(){r=e[Symbol.iterator]()},n:function(){var e=r.next();return a=e.done,e},e:function(e){l=!0,i=e},f:function(){try{a||null==r.return||r.return()}finally{if(l)throw i}}}}function n(e,t){if(e){if("string"==typeof e)return o(e,t);var r=Object.prototype.toString.call(e).slice(8,-1);return"Object"===r&&e.constructor&&(r=e.constructor.name),"Map"===r||"Set"===r?Array.from(e):"Arguments"===r||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(r)?o(e,t):void 0}}function o(e,t){(null==t||t>e.length)&&(t=e.length);for(var r=0,n=new Array(t);r<t;r++)n[r]=e[r];return n}function u(e,t,r){try{if(void 0!==e){if(e=e.toLowerCase().trim(),t=t.toLowerCase().trim(),"strict"===r)return e===t;if("loose"===r)return e.includes(t)||e==t}}catch(n){return console.log("error in matchValues: ".concat(n.message)),!1}return!1}function i(e,t,r){return e.filter(function(e){var n=null,o=[];return!(void 0===e||e.length<=0||Object.keys(e).length<=0)&&(Object.keys(t).forEach(function(n){var i=t[n],a=e[n];o.push(u(a,i,r.matching||"loose"))}),"or"===r.operator&&(n=o.some(function(e){return!0===e})),"and"===r.operator&&(n=o.every(function(e){return!0===e})),n)})}function a(e,t,n,o){var u,a=[{}],l={},c=r(e.feed.entry);try{for(c.s();!(u=c.n()).done;){var f=u.value.gs$cell,s=f.$t,d=f.col,h=f.row,y=l[d];h<2?l[d]=s.toLowerCase():(void 0===a[h]&&(a[h]={}),void 0!==y&&y.length>0&&(a[h][y]=s))}}catch(v){c.e(v)}finally{c.f()}return a=a.filter(function(e){return Object.keys(e).length}),t||!n?a:i(a,n,o)}var l=function(t,r,n){return(0,e.default)(t.sheetId,t.sheetNumber?t.sheetNumber:1).then(function(e){var n=a(e,t.returnAllResults||!1,t.filter||!1,t.filterOptions||{operator:"or",matching:"loose"});r(n)}).catch(function(e){return n(e.message)})},c=l;exports.default=c;
},{"./gsheetsapi.js":"kpsa"}],"l8IH":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=r(require("./gsheetsprocessor.js"));function r(e){return e&&e.__esModule?e:{default:e}}var t=function(r,t,o){return(0,e.default)(r,function(e){t(e)},function(e){if(!o)throw new Error("g-sheets-api error: ".concat(e));o(e)})};module.exports=t;var o=t;exports.default=o;
},{"./gsheetsprocessor.js":"PoGI"}],"H99C":[function(require,module,exports) {
"use strict";var e=t(require("g-sheets-api"));function t(e){return e&&e.__esModule?e:{default:e}}var r="";(0,e.default)({sheetId:"1kRwQDvAJdUPOYSZ5ULORzCA_c4PhNMM0KsKL5ovrNeM",sheetNumber:1,returnAllResults:!0},function(e){e.forEach(function(e){r+=e.data}),localStorage.setItem("Info",r)},function(e){r=e});
},{"g-sheets-api":"l8IH"}]},{},["H99C"], null)
//# sourceMappingURL=/src.27c8b101.js.map